# Generated by Django 5.0.3 on 2024-04-13 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('template_hub', '0001_initial'), ('template_hub', '0002_alter_template_unique_together'),
                ('template_hub', '0003_alter_template_description'), ('template_hub', '0004_template_created_comment'),
                ('template_hub', '0005_alter_comment_created_alter_comment_template_and_more'),
                ('template_hub', '0006_alter_comment_unique_together'),
                ('template_hub', '0007_alter_comment_options_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('downloads', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='template_hub/template_storage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'ordering': ['-downloads'],
                'unique_together': {('user', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=300)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                               to='template_hub.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
                'unique_together': {('template', 'id')},
            },
        ),
    ]
