# Generated by Django 5.0.3 on 2024-04-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_hub', '0002_alter_template_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
