# Generated by Django 5.0.3 on 2024-04-12 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_hub', '0004_template_created_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='template_hub.template'),
        ),
        migrations.AlterField(
            model_name='template',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
