# Generated by Django 5.0.3 on 2024-04-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_hub', '0006_alter_comment_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='created',
            new_name='created_at',
        ),
    ]
