# Generated by Django 5.0.2 on 2024-02-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_group_name_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
    ]
