# Generated by Django 5.0.3 on 2024-03-15 06:40

from django.db import migrations
from django.core.management import call_command


def load_fixtures(apps, schema_editor):
    call_command('loaddata', 'default_groups.json')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_group_user'),
    ]

    operations = [
        migrations.RunPython(load_fixtures)
    ]
