# Generated by Django 5.0.3 on 2024-03-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_add_default_group_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
    ]
