# Generated by Django 4.2.11 on 2024-03-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_group_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_active'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
