# Generated by Django 4.2.11 on 2024-03-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-is_active'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
