# Generated by Django 5.0.3 on 2024-03-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_task_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedJsonHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=55)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='json_file_storage')),
            ],
            options={
                'verbose_name': 'История выгрузки json',
                'verbose_name_plural': 'История выгрузки json',
            },
        ),
    ]
