# Generated by Django 5.0.3 on 2024-03-29 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_exportedjsonhistory_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportedjsonhistory',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exportedjsonhistory',
            name='file',
            field=models.FileField(upload_to='app/json_file_storage'),
        ),
    ]
