# Generated by Django 5.0.3 on 2024-03-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_exportedjsonhistory_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportedjsonhistory',
            options={'ordering': ['-datetime'], 'verbose_name': 'История выгрузки json', 'verbose_name_plural': 'История выгрузки json'},
        ),
    ]
