# Generated by Django 5.0.3 on 2024-04-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_exportedjsonhistory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_complete',
        ),
    ]
